sudo: required
language: clojure
install: true

services:
  - docker

script:
  - bash -c "cd core && lein midje && lein install"
  - bash -c "cd crypt && lein midje"
  - docker run -d -p5672:5672 rabbitmq
  - bash -c "cd rabbit && lein midje"
  - bash -c "cd relational-db && lein midje"

